theme = "kanagawa_custom"

[editor]
rulers = [100]
trim-trailing-whitespace = true
end-of-line-diagnostics = "hint"
completion-trigger-len = 1
completion-timeout = 5
color-modes = true
bufferline = "multiple"
popup-border = "none"
cursorline = true
scrolloff = 5

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = false
wrap-at-text-width = true
wrap-indicator = ""

[editor.statusline]
diagnostics = ["info", "warning", "error"]

[editor.whitespace.render]
tab = "all"
nbsp = "all"
nnbsp = "all"
space = "none"
newline = "none"

[editor.lsp]
display-progress-messages = true


[keys.normal]
"ret" = "goto_word"
C-s = ":u"
C-q = ":bc"

[keys.normal.space]
Q.a = ":bca"
Q.o = ":bco"

[keys.select]
"ret" = "extend_to_word"
"C-[" = "normal_mode"

[keys.insert]
C-backspace = "delete_word_backward"
"C-[" = "normal_mode"

# Option toggles
[keys.normal.space.o]
i = ":toggle-option lsp.display-inlay-hints"

# Macros
[keys.normal.space.m]
# Markdown - check/uncheck checkboxes in lines within selection
c = "@Xs[*|\\-|+] \\[[ |-]\\]<ret>mi]rx,<C-o>"
C = "@Xs[*|\\-|+] \\[[x|X|-]\\]<ret>mi]r ,<C-o>"
A-c = "@Xs[*|\\-|+] \\[[ |x|X]\\]<ret>mi]r-,<C-o>"
