theme = "dark_plus_custom"

[editor]
rulers = [100]
trim-trailing-whitespace = true
end-of-line-diagnostics = "hint"
completion-trigger-len = 1
completion-timeout = 5
color-modes = false
bufferline = "always"
popup-border = "all"
cursorline = true
scrolloff = 10

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = false
wrap-at-text-width = true
wrap-indicator = ""

[editor.statusline]
diagnostics = ["info", "warning", "error"]

[editor.whitespace.render]
tab = "all"
nbsp = "all"
nnbsp = "all"
space = "none"
newline = "none"

[editor.lsp]
display-progress-messages = true

[keys.normal]
"ret" = "goto_word"
C-s = ":u"

[keys.normal.space]
q = ":bc"
Q.a = ":bca"
Q.o = ":bco"

[keys.select]
"ret" = "extend_to_word"
"C-[" = "normal_mode"

[keys.insert]
C-backspace = "delete_word_backward"
"C-[" = "normal_mode"
